#!/usr/bin/env python

import subprocess

subprocess.call([
    'nosetests',
    '--nocapture',
    '--with-coverage',
    '--cover-package',
    'pyptables',
    '--cover-inclusive',
    '--cover-html',
    '--cover-erase',
])
